name: Run it on action

on:
  push:
    branches:
      - master
  schedule:
    - cron: 00 02 * * *

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Working
        env:
          NAME: ${{ secrets.NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          cd /home/runner/work/FUCK-NCO-ZJGSU/FUCK-NCO-ZJGSU
          python3 main-action.py >> out.txt
      - name: curl
        id: enable_workflow
        env:
          REST_TOKEN: ${{ secrets.REST_TOKEN }}
          API_ADDRESS: ${{ secrets.API_ADDRESS }}
        run: |
          echo "Enable Workflow Start..."
          curl -X PUT -H "Authorization: token $REST_TOKEN" "$API_ADDRESS"
          echo "Finished"
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: out
          path: /home/runner/work/FUCK-NCO-ZJGSU/FUCK-NCO-ZJGSU
